# Generated by Django 6.1.1 on 2026-09-16 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedUrl",
            fields=[
                (
                    "code",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=2048,
                        unique=True,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
